items:
  - colors:
      # Default colors
      primary:
        background: '#232627'
        foreground: '#fcfcfc'

        dim_foreground: '#eff0f1'
        bright_foreground: '#ffffff'
        dim_background: '#31363b'
        bright_background: '#000000'

      # Normal colors
      normal:
        black: '#232627'
        red: '#ed1515'
        green: '#11d116'
        yellow: '#f67400'
        blue: '#1d99f3'
        magenta: '#9b59b6'
        cyan: '#1abc9c'
        white: '#fcfcfc'

      # Bright colors
      bright:
        black: '#7f8c8d'
        red: '#c0392b'
        green: '#1cdc9a'
        yellow: '#fdbc4b'
        blue: '#3daee9'
        magenta: '#8e44ad'
        cyan: '#16a085'
        white: '#ffffff'

      # Dim colors
      dim:
        black: '#31363b'
        red: '#783228'
        green: '#17a262'
        yellow: '#b65619'
        blue: '#1b668f'
        magenta: '#614a73'
        cyan: '#186c60'
        white: '#63686d'
  - theme: Breeze
colors:
  # Default colors
  primary:
    background: '#2c2c2c'
    foreground: '#d6d6d6'

    dim_foreground: '#dbdbdb'
    bright_foreground: '#d9d9d9'
    dim_background: '#202020' # not sure
    bright_background: '#3a3a3a' # not sure

  # Cursor colors
  cursor:
    text: '#2c2c2c'
    cursor: '#d9d9d9'

  # Normal colors
  normal:
    black: '#1c1c1c'
    red: '#bc5653'
    green: '#909d63'
    yellow: '#ebc17a'
    blue: '#7eaac7'
    magenta: '#aa6292'
    cyan: '#86d3ce'
    white: '#cacaca'

  # Bright colors
  bright:
    black: '#636363'
    red: '#bc5653'
    green: '#909d63'
    yellow: '#ebc17a'
    blue: '#7eaac7'
    magenta: '#aa6292'
    cyan: '#86d3ce'
    white: '#f7f7f7'

  # Dim colors
  dim:
    black: '#232323'
    red: '#74423f'
    green: '#5e6547'
    yellow: '#8b7653'
    blue: '#556b79'
    magenta: '#6e4962'
    cyan: '#5c8482'
    white: '#828282'
theme: Afterglow

font:
  size: 10
  normal:
    # size: 15
    family: JetBrains Mono
    # Style can be specified to pick a specific face.
    # style: Italic

shell:
  program: zsh
